server {
    listen 8098;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /README.md {
        default_type text/markdown;
        add_header Content-Disposition inline;
    }

    location /assets/ {
        expires 1d;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/plain text/css text/markdown application/javascript application/json;
}
